### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ranajit-jana** [larbigj/camunda-camel-boot#1]
Hi Larbigj,

Thank you for this amazing project .I am getting one error when trying to access the ui (cockpit or process)
Steps
1. built the project
2. started the  boot project from command line
3. trying to access ui via http://localhost:8080
4. click on process definitions
Error which shows  in command line is.

java.lang.RuntimeException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: org.camunda.bpm.engine.repository.ProcessDefinition.getHistoryTimeToLive()Ljava/lang/Integer;

I  am trying  to resolve the same , In case you have some idea. please reply

**Comment by ranajit-jana** [comment]
i have tried to change the  version  to old stable version or latest snapshot version but it did not work.
Does it look like a bug with Camunda code?

<camunda-spring-boot.version>2.3.0-SNAPSHOT</camunda-spring-boot.version>
		<camel.version>2.19.2</camel.version>
		<camunda.version>7.9.0-SNAPSHOT</camunda.version>

**Comment by larbigj** [comment]
Probably you should start with the latest available archetype provided by the camunda team

https://github.com/camunda/camunda-archetypes/tree/master/camunda-archetype-spring-boot

**Comment by ranajit-jana** [comment]
Closed this issue with lower version of the jar as below

<camunda-spring-boot.version>2.1.2</camunda-spring-boot.version>
